import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Mobile App Privacy Policy | Holistic Eco-Resort',
  robots: { index: false, follow: false },
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="space-y-3"><h2 className="text-2xl font-semibold text-emerald-950">{title}</h2><div className="space-y-3 leading-7 text-stone-700">{children}</div></section>;

export default function PrivacyPage() {
  return <main className="min-h-screen bg-stone-50 px-5 py-12"><article className="mx-auto max-w-3xl space-y-9 rounded-3xl bg-white p-7 shadow-sm sm:p-12">
    <header className="space-y-3 border-b border-stone-200 pb-7"><p className="text-sm font-bold tracking-widest text-amber-700">DRAFT — NOT YET PUBLISHED</p><h1 className="text-4xl font-bold text-emerald-950">Holistic Eco-Resort Mobile App Privacy Policy</h1><p className="text-stone-600">Effective date: [publication date]</p><p className="text-sm font-semibold text-emerald-800">Business: Holistic Eco Resort · Owner: Akarsh C K<br />EP-2-200, 200/A, 201, Vanchiyam, Pottamplavu P.O., Kannur, Kerala – 670582, India</p></header>
    <Section title="Who we are"><p>This policy explains how Holistic Eco-Resort handles personal information in the Holistic Eco-Resort mobile app. Questions or privacy requests may be sent to <a className="font-semibold text-emerald-800 underline" href="mailto:booking@holisticstay.in">booking@holisticstay.in</a> or made by calling <a className="font-semibold text-emerald-800 underline" href="tel:+919495850389">+91 94 9585 0389</a>.</p></Section>
    <Section title="Information the app handles"><ul className="list-disc space-y-2 pl-6"><li><strong>Account information:</strong> email address, email-verification status, and the account identifier issued by Amazon Cognito.</li><li><strong>Authentication information:</strong> passwords and verification codes are submitted to Amazon Cognito for authentication. The app does not place passwords or verification codes in ordinary device storage. Authentication session data is stored using the device’s secure storage.</li><li><strong>Booking and stay information:</strong> when a guest searches or prepares a booking, the app may handle guest name, email address, telephone number, dates, occupancy, room and rate-plan selections, prices, taxes, booking references, payment status, and stay status.</li><li><strong>Communications:</strong> information a guest chooses to provide when contacting the resort by telephone, email, WhatsApp, maps, or an external review service is handled by that destination under its own terms and privacy practices.</li></ul><p>The current app does not include advertising or an advertising analytics SDK. It does not collect payment-card details directly. Booking/payment creation remains unavailable unless the resort separately enables a supported payment flow.</p></Section>
    <Section title="Why information is used"><p>Information is used to create and secure guest accounts, verify identity and email ownership, provide requested resort and booking functions, show a guest only their own app-linked stays, respond to support or deletion requests, protect the service against misuse and fraud, and meet applicable business or legal obligations.</p></Section>
    <Section title="Service providers and other systems"><p>Amazon Web Services, including Amazon Cognito and the resort’s AWS-hosted backend, supports account authentication and app services. Simplotel supports resort availability and booking-related records. Information is provided to these services only as needed for the requested function. The resort does not claim that deleting the app account automatically deletes information held in Simplotel or another third-party system.</p></Section>
    <Section title="Security"><p>The app uses encrypted network connections for its public backend and Cognito authentication. Sensitive mobile session information is stored using secure device storage. Access to My Account and My Stays is tied to the authenticated Cognito account; a guest identifier supplied by the mobile client is not accepted as ownership proof.</p></Section>
    <Section title="Retention"><p>Active app-account information is kept while needed to provide and secure the account. When an account is deleted, the Cognito guest account and personal profile or account data controlled by the app are deleted after appropriate verification. Historical booking or transaction records may be retained only for as long as necessary for legitimate business, accounting, tax, fraud-prevention, dispute-resolution, or legal and compliance purposes. No fixed retention period is stated where the applicable system or obligation does not provide one.</p></Section>
    <Section title="Account deletion and privacy requests"><p>A signed-in guest may start deletion from <strong>Delete Account</strong> in the app. A person without the app may follow the instructions at <a className="font-semibold text-emerald-800 underline" href="/account-deletion">the Account Deletion page</a>. The resort will verify the requester’s identity before acting.</p><p>Deleting an app account does not automatically cancel, change, or delete a resort booking, and it does not automatically alter Simplotel records. Retained records are no longer treated as an active mobile-app account.</p></Section>
    <Section title="Age and children"><p>The app and guest-account service are intended for adults aged 18 and over. The app is not directed to children, and a person under 18 should not create or operate a guest account.</p></Section>
    <Section title="Items awaiting owner confirmation"><p>Before publication, the resort must confirm the manual deletion-response process or timeframe and whether any system or legal obligation establishes a specific retention period. This draft does not invent either detail.</p></Section>
    <Section title="Changes to this policy"><p>This policy may be updated when the app, its providers, or applicable requirements change. The published page will show its effective date.</p></Section>
  </article></main>;
}
