import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Delete Your Guest Account | Holistic Eco-Resort', robots: { index: false, follow: false } };

export default function AccountDeletionPage() {
  return <main className="min-h-screen bg-stone-50 px-5 py-12"><article className="mx-auto max-w-3xl space-y-8 rounded-3xl bg-white p-7 shadow-sm sm:p-12">
    <header className="space-y-3 border-b border-stone-200 pb-7"><p className="text-sm font-bold tracking-widest text-amber-700">DRAFT — NOT YET PUBLISHED</p><h1 className="text-4xl font-bold text-emerald-950">Delete your Holistic Eco-Resort guest account</h1><p className="leading-7 text-stone-600">These instructions apply to the Holistic Eco-Resort Android and iPhone guest app.</p><p className="text-sm font-semibold text-emerald-800">Holistic Eco Resort · Owner: Akarsh C K<br />EP-2-200, 200/A, 201, Vanchiyam, Pottamplavu P.O., Kannur, Kerala – 670582, India</p><p className="text-sm font-semibold text-amber-800">Owner confirmation is still required for the manual request-response process or timeframe.</p></header>
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-emerald-950">Request deletion in the app</h2><ol className="list-decimal space-y-2 pl-6 leading-7 text-stone-700"><li>Open the Holistic Eco-Resort app and sign in to your guest account.</li><li>Open <strong>Delete Account</strong> from the menu.</li><li>Review the deletion information, type <strong>DELETE</strong>, and confirm the final deletion prompt.</li><li>The app verifies the authenticated request before deleting the Cognito guest account and clearing its secure session from the device.</li></ol></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-emerald-950">Request deletion without the app</h2><p className="leading-7 text-stone-700">Email <a className="font-semibold text-emerald-800 underline" href="mailto:booking@holisticstay.in?subject=Guest%20account%20deletion%20request">booking@holisticstay.in</a> with the subject <strong>Guest account deletion request</strong>, or call <a className="font-semibold text-emerald-800 underline" href="tel:+919495850389">+91 94 9585 0389</a>. Use the email address associated with the guest account where possible. Do not send a password, verification code, payment-card number, or identity document by ordinary email. The resort will explain the appropriate identity-verification step.</p></section>
    <section className="space-y-3 rounded-2xl bg-emerald-50 p-6"><h2 className="text-xl font-semibold text-emerald-950">What deletion does</h2><p className="leading-7 text-stone-700">After appropriate identity or authentication verification, the guest’s Cognito account and personal profile or account data controlled by the Holistic Eco-Resort app are deleted.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-emerald-950">What may be retained</h2><p className="leading-7 text-stone-700">Deleting the app account does not automatically cancel or alter a booking and does not automatically delete Simplotel records. Historical booking or transaction records that the resort is required to retain for legitimate business, accounting, tax, fraud-prevention, dispute-resolution, or legal and compliance purposes may be retained. They are kept only for as long as necessary for the applicable purpose and are no longer treated as an active app account.</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-emerald-950">Need help?</h2><p className="leading-7 text-stone-700">Contact Holistic Eco-Resort at <a className="font-semibold text-emerald-800 underline" href="mailto:booking@holisticstay.in">booking@holisticstay.in</a> or <a className="font-semibold text-emerald-800 underline" href="tel:+919495850389">+91 94 9585 0389</a>.</p></section>
  </article></main>;
}
